// Curated city + activity catalog for search.
export const CITIES: { city: string; country: string; region: string; tags: string[] }[] = [
  { city: 'Paris', country: 'France', region: 'Europe', tags: ['romantic', 'art', 'food'] },
  { city: 'Rome', country: 'Italy', region: 'Europe', tags: ['history', 'food', 'art'] },
  { city: 'Barcelona', country: 'Spain', region: 'Europe', tags: ['beach', 'culture', 'nightlife'] },
  { city: 'Amsterdam', country: 'Netherlands', region: 'Europe', tags: ['canal', 'art', 'cycling'] },
  { city: 'Lisbon', country: 'Portugal', region: 'Europe', tags: ['coast', 'food', 'history'] },
  { city: 'London', country: 'UK', region: 'Europe', tags: ['museum', 'theatre'] },
  { city: 'Santorini', country: 'Greece', region: 'Europe', tags: ['island', 'sunset'] },
  { city: 'Reykjavik', country: 'Iceland', region: 'Europe', tags: ['nature', 'aurora'] },
  { city: 'Tokyo', country: 'Japan', region: 'Asia', tags: ['food', 'tech', 'culture'] },
  { city: 'Kyoto', country: 'Japan', region: 'Asia', tags: ['temple', 'culture'] },
  { city: 'Bali', country: 'Indonesia', region: 'Asia', tags: ['beach', 'wellness'] },
  { city: 'Bangkok', country: 'Thailand', region: 'Asia', tags: ['food', 'temple', 'nightlife'] },
  { city: 'Singapore', country: 'Singapore', region: 'Asia', tags: ['city', 'food'] },
  { city: 'Seoul', country: 'South Korea', region: 'Asia', tags: ['kpop', 'food'] },
  { city: 'Mumbai', country: 'India', region: 'Asia', tags: ['city', 'food'] },
  { city: 'Jaipur', country: 'India', region: 'Asia', tags: ['heritage', 'palace'] },
  { city: 'Goa', country: 'India', region: 'Asia', tags: ['beach', 'party'] },
  { city: 'Dubai', country: 'UAE', region: 'Middle East', tags: ['luxury', 'desert'] },
  { city: 'Istanbul', country: 'Turkey', region: 'Europe', tags: ['history', 'bazaar'] },
  { city: 'Cairo', country: 'Egypt', region: 'Africa', tags: ['pyramids', 'history'] },
  { city: 'Cape Town', country: 'South Africa', region: 'Africa', tags: ['nature', 'wine'] },
  { city: 'Marrakech', country: 'Morocco', region: 'Africa', tags: ['souk', 'desert'] },
  { city: 'New York', country: 'USA', region: 'Americas', tags: ['city', 'broadway'] },
  { city: 'San Francisco', country: 'USA', region: 'Americas', tags: ['tech', 'bridge'] },
  { city: 'Los Angeles', country: 'USA', region: 'Americas', tags: ['beach', 'movies'] },
  { city: 'Mexico City', country: 'Mexico', region: 'Americas', tags: ['food', 'history'] },
  { city: 'Rio de Janeiro', country: 'Brazil', region: 'Americas', tags: ['beach', 'carnival'] },
  { city: 'Buenos Aires', country: 'Argentina', region: 'Americas', tags: ['tango', 'food'] },
  { city: 'Sydney', country: 'Australia', region: 'Oceania', tags: ['harbour', 'beach'] },
  { city: 'Queenstown', country: 'New Zealand', region: 'Oceania', tags: ['adventure', 'nature'] },
];

import type { Activity } from './types';

export const ACTIVITY_TEMPLATES: Omit<Activity, 'id'>[] = [
  { name: 'City walking tour', category: 'sightseeing', cost: 25, durationHours: 3 },
  { name: 'Local food tasting', category: 'food', cost: 45, durationHours: 2 },
  { name: 'Museum visit', category: 'culture', cost: 18, durationHours: 2 },
  { name: 'Sunset cruise', category: 'sightseeing', cost: 60, durationHours: 2 },
  { name: 'Hiking adventure', category: 'adventure', cost: 35, durationHours: 5 },
  { name: 'Beach day', category: 'nature', cost: 10, durationHours: 4 },
  { name: 'Live music night', category: 'nightlife', cost: 40, durationHours: 3 },
  { name: 'Cooking class', category: 'food', cost: 70, durationHours: 3 },
  { name: 'Local market shopping', category: 'shopping', cost: 50, durationHours: 2 },
  { name: 'Historic landmark visit', category: 'culture', cost: 22, durationHours: 2 },
  { name: 'Snorkeling tour', category: 'adventure', cost: 80, durationHours: 4 },
  { name: 'Spa & wellness', category: 'culture', cost: 90, durationHours: 2 },
  { name: 'Wildlife safari', category: 'nature', cost: 120, durationHours: 6 },
  { name: 'Bike tour', category: 'adventure', cost: 30, durationHours: 3 },
  { name: 'Rooftop dinner', category: 'food', cost: 75, durationHours: 2 },
  { name: 'Boat ride', category: 'nature', cost: 40, durationHours: 2 },
  { name: 'Photography walk', category: 'sightseeing', cost: 20, durationHours: 2 },
  { name: 'Nightlife pub crawl', category: 'nightlife', cost: 55, durationHours: 4 },
];

export const DEFAULT_PACKING: { label: string; category: 'clothing' | 'documents' | 'electronics' | 'toiletries' | 'misc' }[] = [
  { label: 'Passport', category: 'documents' },
  { label: 'Visa & travel insurance', category: 'documents' },
  { label: 'Tickets / boarding passes', category: 'documents' },
  { label: 'Phone & charger', category: 'electronics' },
  { label: 'Power adapter', category: 'electronics' },
  { label: 'Headphones', category: 'electronics' },
  { label: 'T-shirts', category: 'clothing' },
  { label: 'Jeans / pants', category: 'clothing' },
  { label: 'Jacket', category: 'clothing' },
  { label: 'Comfortable shoes', category: 'clothing' },
  { label: 'Toothbrush & toothpaste', category: 'toiletries' },
  { label: 'Sunscreen', category: 'toiletries' },
  { label: 'Medications', category: 'toiletries' },
  { label: 'Sunglasses', category: 'misc' },
  { label: 'Reusable water bottle', category: 'misc' },
];
